import { Archivo_Black, Space_Grotesk } from 'next/font/google'
import { ProgressBarProvider, ProgressBar } from 'react-transition-progress'

import type { Metadata } from 'next'
import './globals.css'

const archivoBlack = Archivo_Black({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-head',
  display: 'swap',
})

const space = Space_Grotesk({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-sans',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${archivoBlack.variable} ${space.variable}`}>
      <body>
        <ProgressBarProvider>
          <ProgressBar className="fixed h-0.5 bg-sky-500 top-0" />
          {children}
        </ProgressBarProvider>
      </body>
    </html>
  )
}
